### ISSUE TITLE
(1.18.2) Showing missing textures

### ISSUE THREAD

**Issue by Y1rd** [tomwmth/cit-reforged#1]
![image](https://github.com/user-attachments/assets/63501d43-95ba-428a-b1c8-2d74f5e9f9fc)
Texture Pack Used: Xail's Enchanted Books
Log (includes mods list): https://mclo.gs/p5g0VJU

**Comment by tomwmth** [comment]
Thanks for the report. Was able to reproduce the issue - will look into fixing this in the next week or two.
