### ISSUE TITLE
Will there be an update to 1.21.1?

### ISSUE THREAD

**Issue by kakashi1464** [tomwmth/cit-reforged#2]

**Comment by tomwmth** [comment]
Eventually there will be an update for 1.21.x, however I cannot guarantee it will be for 1.21.1. I also cannot guarantee it will be released in any reasonable time frame. As explained in the README I mainly create this mod to be used alongside a separate project, which does not yet support 1.21.x Forge.

It would likely be for the eventual final version of 1.21, with additional earlier version(s) if the community ends up using them - for example, many people use 1.20.1 despite it not being the final version of 1.20.

**Comment by kakashi1464** [comment]
I was referring to Neoforge 1.21.1, and I can understand your point, but I think it's already apparent that 1.21.1 will have same fate as 1.20.1

**Comment by tomwmth** [comment]
NeoForge is a possibility at some point in the future but currently I do not have any immediate plans to support it.
